version: '2'
services:
  api:
    image: yaitjebli/pozosapi:v2
    container_name: apirequest
    ports:
      - "8082:80"
    volumes:  
      - $PWD/simple_api/student_age.json:/data/student_age.json

  ihm:
    depends_on:
      - api
    image: php:apache
    environment:
      - USERNAME=toto
      - PASSWORD=python
    volumes:
      - ./website:/var/www/html
    ports:
      - "8081:80"

  registry:
    image: registry:2
    container_name: privaterepo
    volumes:
      - ./website:/var/www/html
    ports:
      - "4000:5000"
    networks:
      - pozosnet

  registry-ui:
    depends_on:
      - registry
    image: joxit/docker-registry-ui
    ports:
      - "4080:80"
    networks:
      - pozosnet
    environment:
      - REGISTRY_URL="http://privaterepo:5000"
      - REGISTRY_TITLE="POZOS CASE"

networks:
 pozosnet:
